# Site settings
title: Technology Consultant
email: tb@tylorbunting.com
url: https://tylorbunting.com
description: "Official landing page for Tylor Buntings Technology Consulting services. Links for various previous projects Tylor Bunting has been involved in and social media sites can be found here."
keywords: "BluePrism; R; SQL; Python; AI; Agile; DevOps; ITIL; machine learning; RPA; Intelligent Automation; Robotic Process Automation"
skills: "RPA | Analytics | Cloud | DevOps"
meta_author: Bunting Tylor

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Tylor

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6D6D6D #18bc9c #80B3FF
  primary-rgb: "109, 109, 109" #"24,288,156" #"128,179,255"
  secondary: 474747 #2c3e50 #FD6E8A
  secondary-dark: 323232 #233140 #A2122F

# Footer settings
footer:
  copyright: Buntoss PTY LTD 2018
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# stackoverflow = https://stackoverflow.com/users/6328183/tylor-bunting?tab=profile
#- title: youtube
#  url: https://www.youtube.com/user/buntossinc/featured?view_as=subscriber
#- title: instagram
#  url: https://www.instagram.com/tylor.bunting/?hl=en

social:
  - title: linkedin
    url: https://au.linkedin.com/in/tylorbunting
  - title: github
    url: https://github.com/tylorbunting
  - title: medium
    url: https://medium.com/@tylorbunting

# Postal address (add as many lines as necessary)
address:
  - line: 3/48 Old Burleigh Road
  - line: Surfers Paradise, QLD 4217

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  clients:
    output: true
